FROM rabbired/alpine-baseimage:latest
MAINTAINER Red Z rabbired@outlook.com

COPY install_qbittorrent.sh /usr/sbin/

# *** install qbitorrent ***
RUN \
  /bin/sh /usr/sbin/install_qbittorrent.sh

# add local files
COPY root/ /

# ports and volumes
EXPOSE 6881 6881/udp 8080 8081
#VOLUME /config /downloads
